runtime: python39  # Gunakan runtime Python 3.9 agar bisa serve file statis

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)
