steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", ".", "gs://$PROJECT_ID-frontend-nopal"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--project", "$PROJECT_ID"]

options:
  logging: CLOUD_LOGGING_ONLY  # Ubah opsi logging agar tidak perlu logs_bucket

