steps:
  # Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend"  # Pastikan lokasi yang benar

options:
  logging: CLOUD_LOGGING_ONLY
