steps:
  # Step 1: Sinkronisasi file ke Cloud Storage (opsional)
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", ".", "gs://$PROJECT_ID-frontend-nopal"]

  # Step 2: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "frontend/app.yaml", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY
