steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-nopal", "."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-nopal"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend-nopal",
        "--image",
        "gcr.io/$PROJECT_ID/backend-nopal",
        "--timeout",
        "600s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/backend-nopal"

options:
  logging: CLOUD_LOGGING_ONLY
